// Code generated by protoc-gen-go. DO NOT EDIT.
// source: CoinPriceChart.proto

package CoinPriceChart

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CoinInfo struct {
	Coin                 string   `protobuf:"bytes,1,opt,name=coin,proto3" json:"coin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CoinInfo) Reset()         { *m = CoinInfo{} }
func (m *CoinInfo) String() string { return proto.CompactTextString(m) }
func (*CoinInfo) ProtoMessage()    {}
func (*CoinInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e264066df25e51ee, []int{0}
}

func (m *CoinInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CoinInfo.Unmarshal(m, b)
}
func (m *CoinInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CoinInfo.Marshal(b, m, deterministic)
}
func (m *CoinInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CoinInfo.Merge(m, src)
}
func (m *CoinInfo) XXX_Size() int {
	return xxx_messageInfo_CoinInfo.Size(m)
}
func (m *CoinInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CoinInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CoinInfo proto.InternalMessageInfo

func (m *CoinInfo) GetCoin() string {
	if m != nil {
		return m.Coin
	}
	return ""
}

type PriceChartInfo struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Timestamp            int64    `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Key                  string   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PriceChartInfo) Reset()         { *m = PriceChartInfo{} }
func (m *PriceChartInfo) String() string { return proto.CompactTextString(m) }
func (*PriceChartInfo) ProtoMessage()    {}
func (*PriceChartInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e264066df25e51ee, []int{1}
}

func (m *PriceChartInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PriceChartInfo.Unmarshal(m, b)
}
func (m *PriceChartInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PriceChartInfo.Marshal(b, m, deterministic)
}
func (m *PriceChartInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PriceChartInfo.Merge(m, src)
}
func (m *PriceChartInfo) XXX_Size() int {
	return xxx_messageInfo_PriceChartInfo.Size(m)
}
func (m *PriceChartInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PriceChartInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PriceChartInfo proto.InternalMessageInfo

func (m *PriceChartInfo) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *PriceChartInfo) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *PriceChartInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*CoinInfo)(nil), "CoinInfo")
	proto.RegisterType((*PriceChartInfo)(nil), "PriceChartInfo")
}

func init() { proto.RegisterFile("CoinPriceChart.proto", fileDescriptor_e264066df25e51ee) }

var fileDescriptor_e264066df25e51ee = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x71, 0xce, 0xcf, 0xcc,
	0x0b, 0x28, 0xca, 0x4c, 0x4e, 0x75, 0xce, 0x48, 0x2c, 0x2a, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x57, 0x92, 0xe3, 0xe2, 0x00, 0x89, 0x7b, 0xe6, 0xa5, 0xe5, 0x0b, 0x09, 0x71, 0xb1, 0x24, 0xe7,
	0x67, 0xe6, 0x49, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x4a, 0x31, 0x5c, 0x7c, 0x08,
	0x3d, 0x60, 0x55, 0x52, 0x5c, 0x1c, 0x69, 0x99, 0x39, 0xa9, 0x7e, 0x89, 0xb9, 0xa9, 0x50, 0x95,
	0x70, 0xbe, 0x90, 0x0c, 0x17, 0x67, 0x49, 0x66, 0x6e, 0x6a, 0x71, 0x49, 0x62, 0x6e, 0x81, 0x04,
	0x93, 0x02, 0xa3, 0x06, 0x73, 0x10, 0x42, 0x40, 0x48, 0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x52, 0x82,
	0x19, 0xac, 0x09, 0xc4, 0x34, 0xb2, 0xe1, 0xe2, 0x43, 0x75, 0x95, 0x90, 0x16, 0x17, 0x17, 0x12,
	0x8f, 0x53, 0x0f, 0xe6, 0x38, 0x29, 0x7e, 0x3d, 0x54, 0x77, 0x28, 0x31, 0x24, 0xb1, 0x81, 0xbd,
	0x60, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x26, 0x6b, 0x3b, 0xfa, 0xda, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CoinPriceChartClient is the client API for CoinPriceChart service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CoinPriceChartClient interface {
	PriceChart(ctx context.Context, in *CoinInfo, opts ...grpc.CallOption) (*PriceChartInfo, error)
}

type coinPriceChartClient struct {
	cc *grpc.ClientConn
}

func NewCoinPriceChartClient(cc *grpc.ClientConn) CoinPriceChartClient {
	return &coinPriceChartClient{cc}
}

func (c *coinPriceChartClient) PriceChart(ctx context.Context, in *CoinInfo, opts ...grpc.CallOption) (*PriceChartInfo, error) {
	out := new(PriceChartInfo)
	err := c.cc.Invoke(ctx, "/CoinPriceChart/PriceChart", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoinPriceChartServer is the server API for CoinPriceChart service.
type CoinPriceChartServer interface {
	PriceChart(context.Context, *CoinInfo) (*PriceChartInfo, error)
}

func RegisterCoinPriceChartServer(s *grpc.Server, srv CoinPriceChartServer) {
	s.RegisterService(&_CoinPriceChart_serviceDesc, srv)
}

func _CoinPriceChart_PriceChart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CoinInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoinPriceChartServer).PriceChart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CoinPriceChart/PriceChart",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoinPriceChartServer).PriceChart(ctx, req.(*CoinInfo))
	}
	return interceptor(ctx, in, info, handler)
}

var _CoinPriceChart_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CoinPriceChart",
	HandlerType: (*CoinPriceChartServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PriceChart",
			Handler:    _CoinPriceChart_PriceChart_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "CoinPriceChart.proto",
}
